version: '3'

services:

  # Servicio para la base de datos
  database:
    build:
      context: ./database
    image: carlosmz87/p1_database:latest
    container_name: p1_database_container
    volumes:
      - p1_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - p1_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  

volumes:
  p1_data:

networks:
  p1_network: