version: '3'

services:

  # Servicio para la base de datos
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: carlosmz87/ayd2_p1_database:latest
    container_name: ayd2_p1_database_container
    volumes:
      - ayd2_p1_data:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - ayd2_p1_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  # Servicio para la aplicación principal (app_service)
  app_service:
    build:
      context: ./backend/app_service
      dockerfile: Dockerfile
    image: carlosmz87/ayd2_p1_app_service:latest
    container_name: ayd2_p1_app_service_container
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - ayd2_p1_network
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} 
      - MYSQL_HOST=${MYSQL_HOST}   
      - DATABASE_PORT=${DATABASE_PORT}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - S3_AWS_ACCESS_KEY_ID=${S3_AWS_ACCESS_KEY_ID}
      - S3_AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_USER_POOL_CLIENT_ID=${COGNITO_USER_POOL_CLIENT_ID}
      - COGNITO_IDENTITY_POOL_ID=${COGNITO_IDENTITY_POOL_ID}
      - COGNITO_AWS_ACCESS_KEY_ID=${COGNITO_AWS_ACCESS_KEY_ID}
      - COGNITO_AWS_SECRET_ACCESS_KEY=${COGNITO_AWS_SECRET_ACCESS_KEY}
    depends_on:
      - database

  # Servicio de notificaciones (producer)
  notification_producer:
    build:
      context: ./backend/notification_service/producer
      dockerfile: Dockerfile
    image: carlosmz87/ayd2_p1_notification_producer:latest
    container_name: ayd2_p1_notification_producer_container
    ports:
      - "${PRODUCER_PORT}:${PRODUCER_PORT}"
    networks:
      - ayd2_p1_network
    environment:
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - PRODUCER_PORT=${PRODUCER_PORT}
    depends_on:
      - auth_service

  # Servicio de notificaciones (consumer)
  notification_consumer:
    build:
      context: ./backend/notification_service/consumer
      dockerfile: Dockerfile
    image: carlosmz87/ayd2_p1_notification_consumer:latest
    container_name: ayd2_p1_notification_consumer_container
    ports:
      - "${CONSUMER_PORT}:${CONSUMER_PORT}"
    networks:
      - ayd2_p1_network
    environment:
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - CONSUMER_PORT=${CONSUMER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - notification_producer

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: carlosmz87/ayd2_p1_frontend:latest
    container_name: ayd2_p1_frontend_container
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - notification_consumer
    restart: always
    networks:
      - ayd2_p1_network
    environment:
      - NEXT_PUBLIC_APP_SERVICE=${NEXT_PUBLIC_APP_SERVICE}
      - NEXT_PUBLIC_AUTH_SERVICE=${NEXT_PUBLIC_AUTH_SERVICE}
      - NEXT_PUBLIC_NOTIFICATION_PRODUCER_SERVICE=${NEXT_PUBLIC_NOTIFICATION_PRODUCER_SERVICE}
      - NEXT_PUBLIC_NOTIFICATION_CONSUMER_SERVICE=${NEXT_PUBLIC_NOTIFICATION_CONSUMER_SERVICE}
      - NEXT_PUBLIC_APP_VERSION=${NEXT_PUBLIC_APP_VERSION}
   
volumes:
  ayd2_p1_data:

networks:
  ayd2_p1_network:
