apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-slave
  labels:
    app: jenkins
    role: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
      role: slave
  template:
    metadata:
      labels:
        app: jenkins
        role: slave
    spec:
      containers:
      - name: jenkins-slave
        image: jenkins/inbound-agent:latest
        args: ["-url", "http://jenkins-master:8080", "jnlp", "${JENKINS_NAME}"]
        env:
        - name: JENKINS_URL
          value: "http://jenkins-master:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
