pipeline {
    agent {
        kubernetes {
            yaml """
            apiVersion: v1
            kind: Pod
            metadata:
              labels:
                agent: multi-stage
            spec:
              containers:
              - name: git
                image: alpine/git
                command:
                - cat
                tty: true
               - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                imagePullPolicy: Always
                command:
                - sleep
                args:
                - 9999999
                volumeMounts:
                - name: jenkins-docker-cfg
                    mountPath: /kaniko/.docker
            volumes:
            - name: jenkins-docker-cfg
                projected:
                sources:
                - secret:
                    name: dockerhub-credentials-secret
                    items:
                        - key: .dockerconfigjson
                        path: config.json
            """
        }
    }

    environment {
        GIT_CREDENTIALS = credentials('Github-credentials')
    }

    stages {
        stage("Checkout") {
            steps {
                container('git') {
                    script {
                        echo "GIT CHECKOUT STAGE"
                        git url: "https://github.com/2730538920101/AYD2_PROYECTO_G2.git", branch: 'develop', credentialsId: "${GIT_CREDENTIALS}"
                    }
                }
            }
        }

        stage("Build and Push Docker Image") {
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    echo "BUILD AND PUSH STAGE"
                    // Navega al directorio del proyecto antes de ejecutar Kaniko
                    dir('backend/app_service') {
                        sh '''#!/busybox/sh
                            echo "FROM jenkins/inbound-agent:latest" > Dockerfile
                            /kaniko/executor --context `pwd` --destination carlosmz87/ayd2-backend:latest 
                        '''
                    }
                }
            }
        }
    }
}
