pipeline {
    agent {
        kubernetes {
            // Definir el template del pod
            label 'docker-pod'
            defaultContainer 'docker'
            yaml """
            apiVersion: v1
            kind: Pod
            metadata:
              labels:
                some-label: my-value
            spec:
              containers:
              - name: docker
                image: docker:latest
                command:
                - cat
                tty: true
              """
        }
    }
    
    stages {
        stage('Execute Docker Command') {
            steps {
                // Ejecutar el comando 'docker ps' dentro del contenedor
                container('docker') {
                    sh 'docker ps'
                }
            }
        }
    }
    
    post {
        always {
            // Limpiar los recursos del pod
            cleanWs()
        }
    }
}
